### ISSUE TITLE
request to publish to npm

### ISSUE THREAD

**Issue by DaJoTo** [davidroman0O/moleculer-cron#14]
Would it be possible to have all the newer goodness in this repository published to the NPM registry?

**Comment by jeam** [comment]
@davidroman0O Please can you publish the changes to npm registry?

**Comment by davidroman0O** [comment]
I've updated `cron` and `moleculer` while updating the usage to fit the `cron` package

**Comment by davidroman0O** [comment]
Version `0.0.4` with `moleculer` in `0.14.32` and `cron` in `1.8.2` https://www.npmjs.com/package/moleculer-cron
