### ISSUE TITLE
Cron does not seem to tick?

### ISSUE THREAD

**Issue by marceliwac** [davidroman0O/moleculer-cron#28]
Thank you for your work on this @davidroman0O !

I'm slightly baffled, I could swear the last time I tried to use this library few months ago, the cron setup would work just fine but it does not seem to work anymore. The jobs are started when the service is created, but never triggered afterwards regardless of the cron pattern (e.g. `* * * * *` (5 asterisks) or `* * * * * *` (6 asterisks)). No matter what I change, this behaviour stays the same -- the job only runs on service creation.

I've tried a minimal example, but even then the issue remains.
```js
// test.js

const { ServiceBroker } = require("moleculer");
const Cron = require("moleculer-cron");

// Create a broker
const broker = new ServiceBroker();

broker.createService({
    name: "cron-job",

    mixins: [Cron],

    crons: [
        {
            name: "JobHelloWorld",
            cronTime: '* * * * * *',
            onTick: async function() {
                console.info('Hello World ticked');
            },
            runOnInit: function() {
                console.info("JobHelloWorld is created");
            },
            onComplete: function() {
                console.info("JobHelloWorld is finished");
            }
        },
    ],
});

// Used to keep the process alive
require('net').createServer().listen();

// Start broker
broker.start()
    .catch(err => console.error(`Error occurred! ${err.message}`));
```

with a package.json that contains only: 

```json
{
  "name": "temp",
  "version": "1.0.0",
  "dependencies": {
    "moleculer": "^0.14.33",
    "moleculer-cron": "^0.0.4"
  }
}
```

Interestingly, I've also tried checking the `getJob('JobHelloWorld').nextUpdates()`, but that returns: unix timestamp + 1min for `* * * * *` (5 asterisks).

Furthermore, the runOnInit function also does not seem to be getting called. It seems related to @habeeth 's (issue #27).

**Comment by marceliwac** [comment]
I've traced this issue to the discrepancy between the code distributed by the npm and the code in this repository... It seems that the repository code runs OK (althought there is a bug with the runOnInit logic which can be fixed pretty easily).

Could you please update the npm package to reflect this repository?

**Comment by davidroman0O** [comment]
Working on it, i will fix other things in the same time

**Comment by davidroman0O** [comment]
Could you double-check me there https://github.com/davidroman0O/moleculer-cron/pull/29 please?

I pushed changed that would fix other issues

**Comment by marceliwac** [comment]
Great work! Let's coordinate this on #29 .
