### ISSUE TITLE
Add a typescript index.d.ts

### ISSUE THREAD

**Issue by sibblegp** [davidroman0O/moleculer-cron#3]
Please add an index.d.ts so that this will work properly with typescript.

**Comment by davidroman0O** [comment]
@sibblegp  Didn't see your message, will do it.

**Comment by Mohammad-Haseeb** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @Moto, @dfinke, @fgbs, @rtmvc, @Michcioperz, @ErikJiang, @Yvees, @Mopip77, @KenMan79, @riscphree, @vinhht95, @liuliuluk, @rogeriomarques, @flightcode, @DearMadMan, @aluxian, @7robbie5, @RifeWang, @kekecoco, @rchicoli

**Comment by marceliwac** [comment]
Hi, is there any progress on this? I would love to see the typescript support for this package as well.

**Comment by davidroman0O** [comment]
Alas, i didn't took take of it in a while
I will free up some time during the next few early mornings

**Comment by davidroman0O** [comment]
Working on it, i will fix other things in the same time

**Comment by davidroman0O** [comment]
pushed
