### ISSUE TITLE
[Question] Concurrency

### ISSUE THREAD

**Issue by chrismbeckett** [davidroman0O/moleculer-cron#5]
How does this service work with regard concurrency control? If you have multiple instances of the cron service on a single node, or instances of the cron service running on multiple nodes, won't this duplicate running the job on every instance?

**Comment by kechkibet** [comment]
I would probably have it run on only a single node and then call a service/event on tick.

**Comment by davidroman0O** [comment]
@chrismbeckett  There is no concurrency control, it's a direct implementation of [Node-Cron](https://github.com/kelektiv/node-cron)!

You can do whatever you want with one node that trigger your events. 

Have fun!
