### ISSUE TITLE
Moleculer peer dependency

### ISSUE THREAD

**Issue by sriharsha-bh** [davidroman0O/moleculer-cron#7]
Need an update on Moleculer peer dependency from 0.11 to 0.14.x. Can this be done?

**Comment by intensite** [comment]
Hello,

I am having this error (see image), could it be related?
![image](https://user-images.githubusercontent.com/7981384/176024952-971b9c98-71aa-4325-98fa-df4d7d817a49.png)

**Comment by davidroman0O** [comment]
@intensite  read the npm documentation, this repo is not stackoverflow `npm i --save XXXXX`

**Comment by intensite** [comment]
Why are you being an ass, this answer has nothing to do with the problem.

**Comment by intensite** [comment]
Your package on NPM had dependency issues.  No need to be a jerk.

**Comment by davidroman0O** [comment]
You're more than welcome to do a pull request

**Comment by davidroman0O** [comment]
Not everyone is natively bilingual, you're on the internet, don't except people to understand exactly what you wrote

It's free open source code, you're are very welcome to do a pull request
